### ISSUE TITLE
Folks outside of RDC group cant make RDC group owner of videos

### ISSUE THREAD

**Issue by AAkindele** [cse-labs/k8s-quickstart#86]
When following the instructions to upload videos to our Stream channels, the "RDC" group does not show up for people outside of the group. They can still upload videos. But they can not make the "RDC" group an owner of the video.

**Comment by bartr** [comment]
That's strange ...

If they make one of us an owner, can we make RDC an owner?

It's probably easier if we always record.

**Comment by AAkindele** [comment]
> If they make one of us an owner, can we make RDC an owner?

Yep. This is the current workaround I used when the issue came up.

**Comment by bartr** [comment]
I added this to our Teams wiki
